### PR TITLE
Fix timestamp parsing

### LINKED ISSUE #33: Rogcat can't parse log messages in the morning until 10
After experimenting a bit:

First variant doesn't work (7:21:49), second does (07:21:49). Both seem to be valid timestamps.

➜  echo "2021-09-24 7:21:49.410 4249 140276332086464 D Test: test" | rogcat -
                                                 ()  -    2021-09-24 7:21:49.410 4249 140276332086464 D Test: test
➜  echo "2021-09-24 07:21:49.410 4249 140276332086464 D Test: test" | rogcat -
07:21:49.410                                Test (4249 140276332086464)  D    test

### PR DESCRIPTION
**Pull request by miklelappo**
This patch introduces fixes parsing of non-prefixed hours
08:10:11 -> correct
8:10:11 -> non-parsed output

Fixes #33

### CODE REVIEW

File: src/parser.rs [hunk 1]
```diff
@@ -64,7 +64,7 @@ named!(
             >> char!('-')
             >> day: flat_map!(take!(2), parse_to!(i32))
             >> space
-            >> hour: flat_map!(take!(2), parse_to!(i32))
+            >> hour: flat_map!(take_until!(":"), parse_to!(i32))
             >> char!(':')
             >> minute: flat_map!(take!(2), parse_to!(i32))
```
Comment (flxo) [inline src/parser.rs:69]: This looks a little bit odd. Why should some device format the hour without a leading zero and the minute not? Same for the seconds.

Comment (miklelappo) [reply src/parser.rs]: Fixed.

**Comment by miklelappo** [comment]
Hi Felix,

any more to-dos on this PR?

Thanks,
Mikhail

**Review by flxo — APPROVED** [review]
LGTM

**Comment by mlappo** [comment]
Thanks!
